title: Pixy Home

custom_header:
  compact_mode: true
  hide_config: true
  footer_mode: true
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)

decluttering_templates: !include lovelace/decluttering_templates/decluttering_templates.yaml

views:
  - !include lovelace/views/00_home_view.yaml
  - !include lovelace/views/10_house_view.yaml
  # # - !include lovelace/views/15_xmas_view.yaml
  # - !include lovelace/views/30_garden_view.yaml
  # - !include lovelace/views/12_security_view.yaml
  # - !include lovelace/views/40_pool_view.yaml
  # - !include lovelace/views/50_watering_view.yaml
