esphome:
  name: led
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "ASUS"
  password: "trucmachinchose"
  manual_ip:
    static_ip: 192.168.1.27
    gateway: 192.168.1.5
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

light:
  - platform: rgb
    name: "bureau leds"
    red: output_component1
    green: output_component2
    blue: output_component3

# Example output entry
output:
  - platform: esp8266_pwm
    id: output_component1
    pin: D1
  - platform: esp8266_pwm
    id: output_component2
    pin: D2
  - platform: esp8266_pwm
    id: output_component3
    pin: D3


binary_sensor:
  - platform: gpio
    name: "Button1"
    pin: D6

